# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: be_tools																							#Pflichtfeld
version: '1.5.4'																								#Pflichtfeld
author: © Falko Müller
supportpage: https://github.com/iceman-fx/be_tools

page:
    title: 'translate:a1510_title' 																			#Werte die mit "translate:" beginnen kommen aus der Sprachdatei.
    perm: be_tools[]
    icon: rex-icon fa-wrench
    subpages:
        default: { title: 'translate:a1510_default' }
        help: { title: 'translate:a1510_help', icon: rex-icon fa-info-circle, itemclass: pull-right }

requires:
    redaxo: '^5.3.0' 																						#benötigt mindestens REDAXO 5.3