package: be_tools
version: '1.9.2'
author: © Falko Müller
supportpage: https://github.com/iceman-fx/be_tools

page:
    title: 'translate:a1510_title'
    perm: be_tools[]
    icon: rex-icon fa-wrench
    subpages:
        default: { title: 'translate:a1510_default' }
        help: { title: 'translate:a1510_help', icon: rex-icon fa-info-circle, itemclass: pull-right }

requires:
    redaxo: '^5.16.0'